### ISSUE TITLE
[multisig] dropdown options should be dynamic based on number of owner addresses that have been created

### ISSUE THREAD

**Issue by nisha-vtvl** [VTVL-co/vtvl-smart-contracts#2]
As there are only 2 owners added, the dropdown should not show '3' as an option and instead, reflect the max number of owners that have been created in the top section.

![Image](https://user-images.githubusercontent.com/116236280/201890870-51395e49-9bc1-44e5-8d73-6c80cde138ca.png)

**Comment by lawrencehui** [comment]
issues tagged to wrong repo
